### ISSUE TITLE
Sync Between GM and Players?

### ISSUE THREAD

**Issue by GambetTV** [theripper93/Splatter#10]
Love the module! Right now if I've got a bunch of blood on my screen and as the GM I click "Clear Blood" it only makes the blood vanish on my screen. Is there a way we could sync it up so that clicking that one button would remove the blood for everyone's screens? I project the player view onto a TV and hide the UI from them, and there's no way to remove the blood effects for them without refreshing, which is kind of a pain.

**Comment by theripper93** [comment]
i might add a clear for all as a macro to not clutter the ui

**Comment by theripper93** [comment]
added a macro in the newest version
