### ISSUE TITLE
Is there a way to turn off the blood drips without healing a token?

### ISSUE THREAD

**Issue by GambetTV** [theripper93/Splatter#11]
Love the module, but is there a way to make a token stop bleeding that doesn't involve healing them past the 50% Health point? Sometimes when combat is over the players have time to patch themselves up but not necessarily heal to full, and it'd be nice if they wouldn't continue bleeding all over the place, haha.

**Comment by theripper93** [comment]
Change any of the settings of the module temporarily , switch the blood color to transparent, or just enable it only in combat. The git is for bug reports use the discord for questsions an pd how tos
