### ISSUE TITLE
[System Request] SWADE works in the other way

### ISSUE THREAD

**Issue by brunocalado** [theripper93/Splatter#12]
Hi! Another great module!

Can you make it work with SWADE? 

SWADE works in a different way.

You don't have any damage when `data.wounds.value = 0`. After you receive damage `data.wounds.value` will increase.

![image](https://user-images.githubusercontent.com/4999783/127718170-9543a6c6-0985-4b9f-b4f3-5120d1fcd693.png)

Thank you anyway.

**Comment by theripper93** [comment]
unfortunately i don't plan to add support for systems with "out of the ordinary" hp mechanics, this works for most and it's what i'm sticking with, that said you are free to fork the project and make a swade specific version
