### ISSUE TITLE
Splatters can be seen behind walls that have no fog of war

### ISSUE THREAD

**Issue by mrjaksauce** [theripper93/Splatter#13]
Heyo! Not sure if this is how Foundry itself works.

Players can see blood splatter inside even if they don't have vision there. They have cleared the fog of war. Every player was outside and could not see indoors to the place with the blood splatter.

(There was a fireball sent through an open window lol)

**Comment by theripper93** [comment]
splatters reside on the background layer, so if that area is explored the blood will be visible if this is not what you are describing please reopen the issue with screenshots

**Comment by mrjaksauce** [comment]
Heyo, that is what I was describing, thanks for the info! :)

**Comment by theripper93** [comment]
yep, that's just "how foundry works"
