### ISSUE TITLE
[Issue] Macro of "set Blood Colorsheet" not working in PF1e system

### ISSUE THREAD

**Issue by vandora03** [theripper93/Splatter#14]
Hi, 

Is it possible to double check and enable the functionality of "set custom Blood colorsheet" macro working under Pf1e system? Thanks.

Regards,
Chris

**Comment by theripper93** [comment]
Unfortunately because of how creature types work on pf you would need a pf specific implementation to make it work. No system specific features will be added. Feel free to fork the module
