### ISSUE TITLE
Minor feature Request - Syncing with the "Health Estimate Module"

### ISSUE THREAD

**Issue by p4535992** [theripper93/Splatter#15]
The module already allows you to change the color of the blood depending on the type of monster.

It would be interesting to have the function for someone like me who uses the "[Health Estimate](https://github.com/mclemente/healthEstimate)" module to be able to see the color of the monster's splatter change according to its HP.

To understand if the monster is at 75% life (Barely Injured) the color of the splatter is a green tending to yellow, if it is at 25% (Badly Injured) a red tending to orange as in the figure:

![img](https://github.com/mclemente/healthEstimate/raw/master/example.png)

**Comment by theripper93** [comment]
Denied
