### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by Doresain** [theripper93/Splatter#16]
Hey, great module, thanks!

Would it be possible to start including release notes with your releases? Even a few brief bullet points would be very helpful. I've tried to understand changes from your commits but they seem to be blank too :(

**Comment by theripper93** [comment]
Changelogs are on my discord

**Comment by Doresain** [comment]
Hey! Following up on this, as I don't think the reply really resolves the issue.

I just went to update this module when moving to v9, and it is *extremely* challenging to figure out what has changed over many versions using your discord. You have a ton of modules (awesome! thank you!) and they are all mixed together. This makes perusing the changes to a particular project extremely cumbersome.

It is pretty standard practice in the Foundry community (and, I think, on github/open source repositories generally?) to include a few release notes in the project. Is there a reason that isn't sufficient for your case?

Thanks!
