### ISSUE TITLE
Player option to turn off Splatter effects

### ISSUE THREAD

**Issue by apoapostolov** [theripper93/Splatter#2]
Yes, squeamish players with potato machines do exist. :( 

Back when Blood and Guts was the main thing to get blood, some players did not like the effects and asked for a way to turn it off personally for their instance. I would love to see such an option added in Splatter, so I get less complaints or a reason to turn it off.

**Comment by theripper93** [comment]
Ye i can just switch the on\off option to client instead of world

**Comment by apoapostolov** [comment]
That would be great, thank you!
