### ISSUE TITLE
Splatter is generated for hidden tokens

### ISSUE THREAD

**Issue by kimitsu** [theripper93/Splatter#20]
Splatter and blood trails may be undesirable for hidden tokens. Since the validity of the issue depends on the situation, a setting may be introduced to provide an option to not generate splatter for hidden tokens.

**Comment by theripper93** [comment]
No option will be added, too situational, if your really need to hide it, change the blood of the creature to transparent

**Comment by kimitsu** [comment]
Attached pull request https://github.com/theripper93/Splatter/pull/21
Please. reconsider. The current operation is not what is expected, players should not be able to see splatter from hidden tokens.
