### ISSUE TITLE
Splatter not working on NPC in 3.5e system?

### ISSUE THREAD

**Issue by BlackWand1** [theripper93/Splatter#22]
I dont get the splatter to work on NPC in the Dnd3.5e system. Not even when pressing the "Bloodsplat token" button.
Any ideas?

**Comment by theripper93** [comment]
errors in the console? is the hp path configured correctly?

**Comment by BlackWand1** [comment]
![image](https://user-images.githubusercontent.com/85252943/132739841-4e419ee5-8092-41ec-8d08-d39fd1fbb815.png)

It works for PC - but not for NPC.
Not sure if the path differs.

Only error I can see if a file to "magic missile" image from another module.

**Comment by BlackWand1** [comment]
Errors:

![image](https://user-images.githubusercontent.com/85252943/132742412-57fd28f4-585e-43e2-b929-7d861572cac3.png)

**Comment by theripper93** [comment]
it seems the creature type is causing issues, try to leavee that empty

**Comment by BlackWand1** [comment]
Left the creature type empty, got this error

![image](https://user-images.githubusercontent.com/85252943/132743418-02e50d2f-4442-44ea-acf9-e525196270a2.png)

**Comment by BlackWand1** [comment]
Unchecked both "creature types" and now it is working!

**Comment by theripper93** [comment]
yep must be a different formatting for the creature type in 3.5, you could try to figure out the correct path or just leave that empty

**Comment by BlackWand1** [comment]
Yeah, maybe you could somehow leave those empty in the module for the 3.5e system?
I am thinking for the other DM:s

**Comment by BlackWand1** [comment]
I could ask the dev for 3.5e about those values, if you want.

**Comment by theripper93** [comment]
i can't change the defaults unfortunatelly :\
