### ISSUE TITLE
Blood doesn't stay on the canvas between sessions

### ISSUE THREAD

**Issue by RuebenMF** [theripper93/Splatter#23]
Blood doesn't remain on the canvas after the server is restarted. Is this intentional?

**Comment by theripper93** [comment]
It is intentional, if you refresh the page or change scene the blood disappears

**Comment by RuebenMF** [comment]
Alright cool, sorry! My splat token macro doesn't seem to be working either but I haven't tested to see if it's a module conflict yet

**Comment by theripper93** [comment]
Don’t think it’s a conflict, does the button in the controls (left bar) work? I might have simply forgotten to update the macro at some point

**Comment by RuebenMF** [comment]
Yeah that works but the macro doesn't. I didn't realise there was an button for it so that's a great workaround for me haha.

Thanks, this (and your other modules) are great :)
