### ISSUE TITLE
Starfinder Incompatible 

### ISSUE THREAD

**Issue by DMJD** [theripper93/Splatter#26]
This doesn't work with the Starfinder system, or if it does it doesn't work in the same way as with DnD5E

**Comment by theripper93** [comment]
Unsupported systems are handled by forks, there is one for swade that might work in a symilar way. How does hp work in star finder ? If it’s not a max hp to zero system splatter won’t work

**Comment by DMJD** [comment]
It's max to zero, also has stamina which is like a shield HP.

**Comment by theripper93** [comment]
If its max to 0 it should work, are you sure you configured the hp path correctly?

**Comment by DMJD** [comment]
Same as DnD5e, but even then it doesn't work when damage is applied.

**Comment by theripper93** [comment]
installed starfinder, works completely fine on my end 
![image](https://user-images.githubusercontent.com/1346839/139705275-09bd4214-bf00-4b70-8ade-8dfe54ecbb01.png)

**Comment by theripper93** [comment]
i just removed 7 hp (from 11)

**Comment by theripper93** [comment]
make sure your settings are correct and that there arent modules interfeering

**Comment by DMJD** [comment]
Awesome, thanks!  How would I know if modules are interfering?

**Comment by theripper93** [comment]
you disable every module except splatter and see if the issue persists, if you still ahve issues feel free to join my discord, the issue tracker is reserverd for bugs

**Comment by DMJD** [comment]
Thanks for the tip!
