### ISSUE TITLE
bug when using splatter with animated tokens

### ISSUE THREAD

**Issue by MN88** [theripper93/Splatter#27]
Splatter doesnt seem to work with animated tokens, I used free content from Vivid adventures: https://www.patreon.com/vividadventuremaps

i get the following console error code (when used on a wolf):
Uncaught TypeError: Cannot use 'in' operator to search for 'custom' in Beast
[Detected 1 package: splatter]
    at Function.Object.byString (main.js:7)
    at Function.getCreatureTypeCustom (BloodSplatter.js:242)
    at BloodSplatter.creatureType (BloodSplatter.js:138)
    at BloodSplatter.SplatFromToken (BloodSplatter.js:40)
    at Function.generateSplat (BloodSplatter.js:274)
    at BloodSplatter.js:338
    
    similar errors are present for other creatures:
    Uncaught TypeError: Cannot use 'in' operator to search for 'custom' in Giant
    Uncaught TypeError: Cannot use 'in' operator to search for 'custom' in Humanoid (goblinoid)
    Uncaught TypeError: Cannot use 'in' operator to search for 'custom' in Undead

**Comment by theripper93** [comment]
That’s not related to animated tokens, what system are you using?

**Comment by MN88** [comment]
Latest 5e version. I can send u a game inv if you want to check it out

**Comment by theripper93** [comment]
That's indeed strange - could you send an export of the creature that's causing issues? in the mean time following this will solve it for now 
![image](https://user-images.githubusercontent.com/1346839/146658322-fb6b707c-af97-4dd9-ba97-8fafe29a9ac8.png)

**Comment by MN88** [comment]
github wont let me drag and drop json files to a comment :/

**Comment by theripper93** [comment]
upload to any file sharing website and send the link ;)

**Comment by theripper93** [comment]
Issue was the outdated data structure of the actor - closed
