### ISSUE TITLE
/Logs/error.log: Invalid language definition in Package splatter

### ISSUE THREAD

**Issue by yjeroen** [theripper93/Splatter#29]
{"level":"error","message":"Invalid language definition in Package splatter: Language JSON path lang/ja.json does not exist","timestamp":"2022-01-06 14:43:33"}

{"level":"error","message":"Invalid language definition in Package splatter: Language JSON path lang/ja.json does not exist","timestamp":"2022-01-06 14:52:10"}

**Comment by theripper93** [comment]
fixed
