### ISSUE TITLE
Possible performance issues with multi-level token

### ISSUE THREAD

**Issue by BrotherSharper** [theripper93/Splatter#3]
Hey, thanks for bringing back blood splatting!
Blood n Guts had massive performance issues with multi-level token mod, wherein it caused the shadows of tokens seen from a different level to also spew blood. (The machine had to render a shit ton of blood and got extremely laggy)
Perhaps you have already thought about it but just letting you know if you want to investigate it.

**Comment by theripper93** [comment]
i'm pretty sure that this implementation just does nothing with the mirrored tokens, that's assuming they even work, they are just buggy af from my testing. But, assuming it works Splatter will not draw blood if the token has no actor wich is the case for mlt mirrored tokens
