### ISSUE TITLE
Changelogs?

### ISSUE THREAD

**Issue by Doresain** [theripper93/Splatter#30]
Hey, following up on the closed #16 as I don't believe your response re: changelogs in discord resolves the issue.

I just went to update this module when moving to v9, and it is extremely challenging to figure out what has changed over many versions using your discord. You have a ton of modules (awesome! thank you!) and they are all mixed together. This makes perusing the changes to a particular project extremely cumbersome.

It is pretty standard practice in the Foundry community (and, I think, on github/open source repositories generally?) to include a few release notes in the project. Is there a reason that isn't sufficient for your case?

Thanks!

Changelogs are on my discord

_Originally posted by @theripper93 in https://github.com/theripper93/Splatter/issues/16#issuecomment-896764933_

**Comment by theripper93** [comment]
sorry but i don't do changelogs outside of the discord ones, the only thing that changed is the syntax to generate the splatter mask since the wall method changed - also even if you don't change it it should still work in v9 anyways (but not in v10)
