### ISSUE TITLE
BUG: "Clear Blood" button only clears it on your screen, no one else's.

### ISSUE THREAD

**Issue by GambetTV** [theripper93/Splatter#33]
When the GM hit the Clear Blood Button, this used to clear blood for everyone, but now only clears it for the person pushing the button. It'd be great if you could restore this functionality, or at least make it an option the GM could set, as sometimes removing blood is about clearing a scene and not just Foundry performance. Thanks!

**Comment by theripper93** [comment]
That neveer worked as you are saying, it always only cleeared blood for the client only, there is a macro included to clear it on all clients.
