### ISSUE TITLE
Request - recolor already splatted blood

### ISSUE THREAD

**Issue by dmrickey** [theripper93/Splatter#34]
I often forgot to recolor blood appropriately until it's too late. Since the built in button only clears blood locally (though as the GM client it would be amazingly awesome if it had a modal with a question to "clear for me" or "clear for everyone" (though honestly as the GM that button isn't useful because it doesn't clear it for everyone--I have no reason to clear for _only_ me as the gm)).. Ok tangent aside. It would be nice if the blood splatters had a reference back to their "parent" token. So if the "parent" token's blood is updated, then all of the splattered blood would update to be the appropriate color.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

**Comment by dmrickey** [comment]
My apologies, I'd read it before but apparently not recently enough to remember the portion about feature requests.
