### ISSUE TITLE
Splat Token macro doesn't work

### ISSUE THREAD

**Issue by lektu** [theripper93/Splatter#35]
> BloodSplatter.js:205 Uncaught (in promise) TypeError: tokens.map is not a function
> [Detected 1 package: splatter]
>     at Function.socketSplat (BloodSplatter.js:205)
>     at eval (eval at _executeScript (foundry.js:16907), <anonymous>:5:15)
>     at Macro.eval (eval at _executeScript (foundry.js:16907), <anonymous>:6:7)
>     at Macro._executeScript (foundry.js:16909)
>     at Macro.execute (foundry.js:16866)
>     at Hotbar._onClickMacro (foundry.js:52252)
>     at HTMLLIElement.dispatch (jquery.min.js:2)
>     at HTMLLIElement.v.handle (jquery.min.js:2)

Works after changing 

```
if(!_token) return;
BloodSplatter.socketSplat(_token)
```

to

```
if(!_token) return;
BloodSplatter.socketSplat([_token])
```

(I'm assuming the macro is intended to work on a single token.)

**Comment by theripper93** [comment]
The macro should now work
