### ISSUE TITLE
Invert Healtlevel

### ISSUE THREAD

**Issue by patrickmohrmann** [theripper93/Splatter#36]
Hi, would it be possible to include an option to invert the splatter happen the other way around.. I play several games. where you count the damage up to the Deathrating.

Thank you

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
