### ISSUE TITLE
With option "Wall block blood" the modul doing nothing

### ISSUE THREAD

**Issue by R0TEAM** [theripper93/Splatter#37]
As in Title ...
If the option "Wall block blood" active ... no blood is created ...
not from HP decrase ... and not from manual select one token and press the splatter button

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
