### ISSUE TITLE
PF1 support

### ISSUE THREAD

**Issue by dmrickey** [theripper93/Splatter#39]
Here are the settings for PF1 support

![image](https://user-images.githubusercontent.com/3664822/161662679-b12f0559-7e68-407b-9d6f-68ccb595bda8.png)
Creature Type (and Custom): `document.race.data.data.creatureType`
Leave HP as is.

Here's a script macro to setup some default colors for the different creature types found in pf1
```
const bloodSheetData = {
  aberration: "#b527d5d5",
  animal: "#a51414d8",
  construct: "#5f4d39d5",
  dragon: "#40ab26d8",
  fey: "#b304add8",
  magicalBeast: "#b71e46d8",
  humanoid: "#a51414d8",
  monstrousHumanoid: "#810808d8",
  ooze: "#0000cc6d8",
  plant: "#195d09d8",
  undead: "#260000d8",
  outsider: "#b304add8",
  vermin: "#195d09d8",
};

game.settings.set("splatter", "BloodSheetData", bloodSheetData);
```

I'm not sure what to do with this info, but if someone comes here looking for it, even if this issue is closed, if they look close enough they'll be able to find it.

**Comment by theripper93** [comment]
Added a file to the repo where users can contribute configurations https://github.com/theripper93/Splatter/blob/main/CONFIGURATIONS.MD
