### ISSUE TITLE
module fails to update

### ISSUE THREAD

**Issue by wmve** [theripper93/Splatter#43]
when i do an update on all modules, i get this

<img width="297" alt="SNAG-1995" src="https://user-images.githubusercontent.com/55966777/178152651-290bbe7f-6221-4c1d-bc16-ed7e11faeb31.png">

when i do a manual install using the manifest i get this

![image](https://user-images.githubusercontent.com/55966777/178152630-8b1d06f1-21c1-42a2-8073-1836088024ed.png)

**Comment by theripper93** [comment]
The module is now updated for v10, v9 does not correctly read the new v10 manifest

**Comment by wmve** [comment]
well, ok, but then a more meaningful error message than "k is not defined"
might make sense.
why do we have to break the update process for every user who chooses not
to go to V10?  is this going to happen with every module that goes to V10
and leaves people behind on V9?

**Comment by wmve** [comment]
Sent from my Galaxy
-------- Original message --------From: theripper93 ***@***.***> Date: 2022-07-10  13:30  (GMT-05:00) To: theripper93/Splatter ***@***.***> Cc: wmve ***@***.***>, Author ***@***.***> Subject: Re: [theripper93/Splatter] module fails to update (Issue #43) 
Closed #43 as completed.
