### ISSUE TITLE
Relatively massive HP loss can cause absurdly huge splashes

### ISSUE THREAD

**Issue by guillaume-gc** [theripper93/Splatter#45]
I love how blood splashes scale with HP loss, but it seems there is no maximum amount.

See what happens when a character with 175 HP loses 10000 HP:
![image](https://user-images.githubusercontent.com/15614283/180247853-79df017c-acff-431a-bfc6-854bb09a4df1.png)

I know it's practically impossible to deal so much damage, but since it's relative, what could happen is a low level character gets attacked by a high level opponent.

Here's what happens when a character with 8 HP loses 80 HP:
![image](https://user-images.githubusercontent.com/15614283/180249022-f7f6aacd-5e4e-4f8f-8968-6754a191f884.png)

I think a max scaling threshold option could solve this problem! :)

**Comment by theripper93** [comment]
Sorry but this is to much of an edge case to warrant bloating the settings
