### ISSUE TITLE
"Set custom BloodSheet" macro does not work in v10

### ISSUE THREAD

**Issue by XtraButtery** [theripper93/Splatter#48]
**ALL OTHER MODULES DISABLED?** Yes, excluding Splatter's dependencies and Forge's mandatory module.
**Module:** Splatter (3.0.7)
**Conflicting Module (if applicable)**: n/a
**Foundry and System version**: Foundry Virtual Tabletop Version 10 Build 288 + DnD5e 2.0.3
**OS, Hosting, Browser (if applicable)**: Linux, Forge-VTT hosting, tested in both Vivaldi (Chromium) and Firefox browsers.
**Short Description of bug**: Custom blood colours set through the included macro are not being applied.
**Simple steps to reproduce the bug**: Create a token of any creature type after configuring blood using the included macro. The blood will not be correctly colour to the macro.

Setting blood colour manually through the token's setting still works as normal.
**Screenshots and/or console errors**:
![image](https://user-images.githubusercontent.com/35461692/197561350-15faae34-505d-4b62-932c-3f636ba5352f.png)

I have tested and confirmed this in both my live game and a fresh world.

**Comment by theripper93** [comment]
fixed
