### ISSUE TITLE
Cyberpunk RED Incompatible

### ISSUE THREAD

**Issue by Mewcualar** [theripper93/Splatter#49]
Been unable so far to get it to interface with the HP in CPRED, not sure if user error (me) or something else

Link to CPRED module: https://gitlab.com/JasonAlanTerry/fvtt-cyberpunk-red-core

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
