### ISSUE TITLE
[Bug] Bloodsplats no longer appear on tiles

### ISSUE THREAD

**Issue by r-valyar** [theripper93/Splatter#50]
I am using tiles to build the scenes in Conan 2d20 (or any other system) and rarely use background image to represent the combat map. I found out that bloodplatters are no longer showing on top of the tiles as before and they render on the background layer (I think), which hides them from view when I build tile-based map. 

I think it is good to have some control in settings or fix to visualize the bloodsplats on top of tiles that are not roof tiles.

Here is screenshot of the issue:
![image](https://user-images.githubusercontent.com/63558984/205434007-85242893-cd64-47fd-8478-2a1bb2cf18e1.png)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
