### ISSUE TITLE
[BUG] Bloodplats no longer show on tiles

### ISSUE THREAD

**Issue by r-valyar** [theripper93/Splatter#51]
**ALL OTHER MODULES DISABLED?** false

**Module:** Splatter 3.0.8

**Conflicting Module (if applicable)**: No conflicts with modules, this happens in every system I tested, tiles just cover the bloodplat

**Foundry and System version**: Foundry v10.291; Conan 2d20 1.7.1

**OS, Hosting, Browser (if applicable)**: Firefox 107, MS Edge 107

**Short Description of bug**: Bloodsplats are hidden by tiles and no longer visible on top as before. 

**Simple steps to reproduce the bug**:  Create new scene, add tiles, drag token and click splatter button or reduce token's HP to produce a splat. Screenshot below

**Screenshots and/or console errors**:
![image](https://user-images.githubusercontent.com/63558984/205434778-6e0e3f49-23f9-4d57-a3c5-1e5c611cdbed.png)

**Comment by theripper93** [comment]
fixed

**Comment by r-valyar** [comment]
Awesome, thanks for the quick fix!!! :)
