### ISSUE TITLE
Add option to splash blood depending from damage type.

### ISSUE THREAD

**Issue by yuri-ccp** [theripper93/Splatter#58]
Almost all TTRPG have many damage type in their specifications with some different mechanics and many of these damage aren't physical nor bleed or only bleed after some massive damage.

The main idea here is add an option to restrict the splatter to only splash blood to just some damage type like piercing and slashing and ignore all other damages or limit it to some situation like crits in bludgeoning (representing some exposed fracture).

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
