### ISSUE TITLE
No Splatter Showing on Player Screen (Browser)

### ISSUE THREAD

**Issue by Lobosolo85** [theripper93/Splatter#6]
Hello!  I am new to using splatter.  I have it working on the Foundry desktop client and I have it enabled.  When I connect as a player through the chrome browser to test it out, the player cannot see any splatters.  I verified that Splatter is configured to "enable bloodsplats" in the player options.

Is this a known issue with using a browser to connect?  I have the same issue whether I use Chrome or Edge as a browser.

It is probably user error, but I thought I would check.  Thank you for making cool modules for us to use in our games!

Lobosolo85

**Comment by theripper93** [comment]
the splatters are not persistent and not saved on the scene, are new splatters not showing?

**Comment by theripper93** [comment]
actually you are correct, i must have messed up something, gimme 1 hour and i'll fix it

**Comment by theripper93** [comment]
should be fixed
