### ISSUE TITLE
Bloodsplats even if the token has a certain condition

### ISSUE THREAD

**Issue by peterprokurist** [theripper93/Splatter#61]
Is it possible to configure the module to generate bloodspsplats even when the token gets a certain (self-defined) condition, such as "Bleeding Wound" or "Mutilated"? regardless of the HP lost (DnD) or the wounds suffered (SWADE)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
