### ISSUE TITLE
question:  does creatureType: support comma delimited lists?

### ISSUE THREAD

**Issue by dodds-steven** [theripper93/Splatter#65]
I'm looking to add [Advanced Roleplaying System (ARS)](https://foundryvtt.com/packages/ars), a Dnd 1e 2e system. In order to get bloodSheetData working, I think those paths need to be none blank? 
I found the path to ARS' creature types here: `_token.actor.system.details.type`
however this contains a comma delimited list of types, not just a single type value. 

Example: `'Wight, Nocturnal, Undead'`

Does Splatter parse the list to find the undead value?  when I run the bloodSheetData macro, colors do not change, with my paths set like below. 

```
          creatureType: "details.type", // this is a comma delimited list
          creatureTypeCustom: "", // maybe should match creatureType? it's not clear to me what this is.
          currentHp: "attributes.hp.value", // works
          maxHp: "attributes.hp.max",  // works
```

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
