### ISSUE TITLE
[feature request] blood directely to the token

### ISSUE THREAD

**Issue by CaosFR** [theripper93/Splatter#69]
Hi,

Simple feature request.

Can you create a option to add blood directely on the token body instead of on the floor of the maps ?

Thanks

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.

**Comment by CaosFR** [comment]
Sorry, it's now post as you requested
